### ISSUE TITLE
PS4 controller input is not being detected/processed.

### ISSUE THREAD

**Issue by AlejoAsd** [berithpy/ggj#20]

**Comment by AlejoAsd** [comment]
This is specific to our game due to the recent gamepad changes. Phaser examples detected the input correctly.

**Comment by berithpy** [comment]
I'll test it with the gamepads I have available

**Comment by AlejoAsd** [comment]
Commit https://github.com/berithpy/ggj/pull/16/commits/b1543beaa0cbf7fda8a1416659cd54ac7086a8f3 fixed this.
